trigger: 
 - master

pool:
   name: 'cgi-ado-agents-small'

steps: 
- task: GoTool@0
  displayName: 'Set GoLang version'
  inputs:
    version: '1.18.2'
- task: Go@0
  displayName: 'Install Go'
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: 'Install dependency'
  inputs:
    command: 'mod'
    arguments: 'download'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: 'Build App'
  inputs:
    command: 'build'
    arguments: '-o go-sample-app'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CmdLine@2
  inputs:
    scripts: ls -la
    workingDirectory: '$(System.DefaultWorkingDirectory)'